name: CIFuzz
on:
  push:
    branches: [ java15 ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ java15 ]
  schedule:
    - cron: '43 11 * * 2'
permissions: read-all
jobs:
 BatchFuzzing:
   runs-on: ubuntu-latest
   strategy:
     fail-fast: false
   steps:
   - name: Build Fuzzers
     id: build
     uses: google/clusterfuzzlite/actions/build_fuzzers@v1
     with:
       language: jvm
       sanitizer: address
   - name: Run Fuzzers (batch)
     id: run
     uses: google/clusterfuzzlite/actions/run_fuzzers@v1
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       language: jvm
       fuzz-seconds: 300
       mode: batch
       sanitizer: address
       storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/johannes-riecken/pacman-java-storage.git
       storage-repo-branch: main   # Optional. Defaults to "main"
       storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
   - name: Run Fuzzers (coverage)
     id: run
     uses: google/clusterfuzzlite/actions/run_fuzzers@v1
     with:
       github-token: ${{ secrets.GITHUB_TOKEN }}
       language: jvm
       fuzz-seconds: 300
       mode: coverage
       sanitizer: address
       storage-repo: https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/johannes-riecken/pacman-java-storage.git
       storage-repo-branch: main   # Optional. Defaults to "main"
       storage-repo-branch-coverage: gh-pages  # Optional. Defaults to "gh-pages".
